export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_SIDEBAR_TWO = 'TOGGLE_SIDEBAR_TWO'

export const TOGGLE_SIDEBAR_TWO_DATA = 'TOGGLE_SIDEBAR_TWO_DATA'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const LOGOUT = 'LOGOUT'

export const REPO_STATE_UPATE = 'REPO_STATE_UPATE'
export const REPO_URL_UPATE = 'REPO_URL_UPATE'
export const REPO_UPATE = 'REPO_UPATE'
