export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const TOGGLE_SIDEBAR_TWO = 'TOGGLE_SIDEBAR_TWO'

export const TOGGLE_SIDEBAR_TWO_DATA = 'TOGGLE_SIDEBAR_TWO_DATA'

export const TOGGLE_SIDEBAR_BLOGDATA = 'TOGGLE_SIDEBAR_BLOGDATA'

export const TOGGLE_BLOGDATA = 'TOGGLE_BLOGDATA'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SELECT_POST = 'SELECT_POST'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const LOGOUT = 'LOGOUT'

export const REPO_STATE_UPATE = 'REPO_STATE_UPATE'
export const REPO_URL_UPDATE = 'REPO_URL_UPDATE'
export const SELECT_WEBSITE = 'SELECT_WEBSITE'
export const REPO_UPATE = 'REPO_UPATE'
