FROM node:latest as intermediate

COPY package*.json ./code/

RUN cd /code && \
    sed -ri '/file:/ s/^(.*)//g' package.json && \
    npm i

COPY forms-schema /code/forms-schema/
RUN cd /code/ && \
    npm i -S forms-schema

COPY selo /code/selo/
RUN cd /code/selo && \
    npm i --only=production && \
    npm run release && \ 
    cd /code/ && \
    npm i -S selo

COPY vue-authenticate /code/vue-authenticate/
RUN cd /code/ && \
    npm i -S vue-authenticate

COPY vfg-field-array /code/vfg-field-array/
RUN cd /code/ && \
    npm i -S vfg-field-array

COPY . /code/.

RUN cd /code && \
    npm run build

# No need for this due to cloudfront ??
# RUN sed -ri 's~/assets/~/admin/assets/g' /code/index.html

FROM nginx:alpine
ADD .docker/config/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=intermediate /code/public/ /www/public/

# Cannot use http for now as
# websites.acentera.com hostname is required ...
# HTTP /.acentera_internal_lbcheck

ENV SERVICE_NAMESPACE "acentera"
ENV SERVICE_80_NAME "admin-static"
ENV SERVICE_80_NAME "admin-static"
ENV SERVICE_80_TAGS "_http_"
# optional, Consul default used otherwise
ENV SERVICE_80_CHECK_HTTP /
ENV SERVICE_80_CHECK_INTERVAL 15s
ENV SERVICE_80_CHECK_TIMEOUT 1s
