FROM node:11.15.0-alpine as intermediate

COPY package*.json ./code/

RUN apk add --no-cache make git gcc g++ python && \
  npm install --unsafe-perm --verbose -g node-sass  node-gyp && \
  apk del make gcc g++ python

RUN cd /code && \
    sed -ri '/file:/ s/^(.*)//g' package.json && \
    apk add --no-cache make git gcc g++ python && \
    npm i && \
    apk del make gcc g++ python

COPY forms-schema /code/forms-schema/
RUN cd /code/ && \
    npm i -S forms-schema

COPY selo /code/selo/
RUN cd /code/selo && \
    npm i --only=production && \
    npm run release && \ 
    cd /code/ && \
    npm i -S selo

COPY vue-authenticate /code/vue-authenticate/
RUN cd /code/ && \
    npm i -S vue-authenticate

COPY vfg-field-array /code/vfg-field-array/
RUN cd /code/ && \
    npm i -S vfg-field-array

COPY . /code/.

RUN cd /code && \
    npm run build && \
    D=$(date +%s) && \
    mv public/assets/js/app.js public/assets/js/app-${D}.js && \
    mv public/assets/js/vendor.js public/assets/js/vendor-${D}.js && \
    sed -ri "s~/js/app.js~/js/app-${D}.js~g" public/index.html && \
    sed -ri "s~/js/vendor.js~/js/vendor-${D}.js~g" public/index.html && \
    echo ${DT} > public/health.html

# No need for this due to cloudfront ??
# RUN sed -ri 's~/assets/~/admin/assets/g' /code/index.html

FROM nginx:alpine
COPY --from=intermediate /code/public/ /www/public/
ADD .docker/config/nginx.conf /etc/nginx/conf.d/default.conf

# Cannot use http for now as
# websites.acentera.com hostname is required ...
# HTTP /.acentera_internal_lbcheck

ENV SERVICE_NAMESPACE "acentera"
ENV SERVICE_80_NAME "admin-static"
ENV SERVICE_80_NAME "admin-static"
ENV SERVICE_80_TAGS "_http_"
## optional, Consul default used otherwise
ENV SERVICE_80_CHECK_HTTP /health.html
ENV SERVICE_80_CHECK_INTERVAL 15s
ENV SERVICE_80_CHECK_TIMEOUT 1s
